#!/bin/sh

config=${XDG_CONFIG_HOME:-$HOME/.config}/redlite/urls
cache=${XDG_CACHE_HOME:-$HOME/.cache}/redlite

# ensure stuff exists
mkdir -p "$cache"
mkdir -p `dirname "$config"`
touch "$config"

# shows the usage message
usage() {
    echo "usage: redlite ( -s | -q | -o | -c ) [-v]"
    echo "  -s :  scan for updates"
    echo "  -q :  list all diffs"
    echo "  -o :  open all diffs"
    echo "  -c :  delete all diffs"
    echo "  -v :  be verbose (must come last)"
    echo
    echo "config file: $config"
    echo "cache directory: $cache"
}

# scans for changes
# exits with non-zero status if something changed
scan() {
    # remove comments
    urls=`grep -v "^#" "$config"`
    changed=""

    IFS='
'
    for params in $urls
    do
        url=`echo $params | awk -F '\t' '{print $1}'`
        clean_url=`echo "$url" | sed 's/[^a-zA-Z0-9_.-]/_/g'`
        file="$cache/$clean_url"
        diff="$file.diff.html"

        [ -n "$verbose" ] && echo "Scanning $params..."

        [ -n "$verbose" ] && echo "wget -q --user-agent=Firefox -O - $params > '$file.new'"
        sh -c "wget -q --user-agent=Firefox -O - $params > '$file.new'"
        if [ "$?" != "0" ]
        then
            [ -n "$verbose" ] && echo "wget error! Ignoring this URI."
            continue
        fi

        # don't alert on first time get
        if [ ! -f "$file" ]
        then
            [ -n "$verbose" ] && echo "First time scan. No diff generated."
            mv "$file.new" "$file"
            continue
        fi

        # otherwise: see if things changed
        if ! diff -q -w "$file" "$file.new" > /dev/null
        then
            [ -n "$verbose" ] && echo "$url changed! Generating diff at $diff."
            changed="true"
            dir=`dirname $0`
            $dir/html-diff.py "$file" "$file.new" |
                sed 's/<head>/\n<head>\n/' |
                sed '/<head>/ a\
<head><base href="'"$url"'"/><style type="text/css"><!--ins {background: #bfb} del{background: #fcc} ins,del {text-decoration: none} --></style>' |
                sed '1,/class="diff/s/class="diff/id="first-diff" &/' > "$diff"
        fi
    done

    [ -z "$changed" ] && exit 0
    [ -n "$changed" ] && exit 1
}

# lists all the diff files available on stdout
query () {
    for diff in "$cache"/*.diff.html
    do
        [ -e "$diff" ] && echo "$diff"
    done
}

# opens all the diff files available
open () {
    if [ -x "$BROWSER" ]
    then
        for diff in "$cache"/*.diff.html
        do
            [ -e "$diff" ] && eval "$BROWSER file://$diff#first-diff"
        done
    else
        echo "Browser ($BROWSER) is not executable. Aborting."
    fi
}

# removes all the diff files and marks all files as unchanged
clear() {
    for diff in "$cache"/*.diff.html
    do
        file=`echo "$diff" | sed 's/\.diff\.html$//'`
        mv "$file.new" "$file"
        rm "$diff"
    done
}

[ "$2" == "-v" ] && verbose="true"
case "$1" in
    (-s) scan  ;;
    (-q) query ;;
    (-o) open  ;;
    (-c) clear ;;
    (*)  usage ;;
esac

